Resources:
  PookieDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pookie-data-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
